name: Build and push PHP 8.1
on:
  push:
    paths:
      - 'php/**'
      - '.github/workflows/php-81.yml'

jobs:
  deploy:
    uses: ./.github/workflows/build-push.yml
    with:
      build_arg: PHP_VERSION=8.1.20
      dir: php
    permissions:
      contents: read
      id-token: write
    secrets: inherit
